# Generated by Django 4.2.7 on 2023-11-07 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(help_text='Avtor haqida', verbose_name='Avtor haqida'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Avtorning tug'ilgan kunini kiritng!", null=True, verbose_name="Avtorning tug'ilgan kuni"),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='Avtorning ismini kiriting!', max_length=100, verbose_name='Avtorning ismi'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='Avtorning familyasini kiriting!', max_length=100, verbose_name='Avtorning familyasi'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, help_text='Avtorning rasimini kiriting!', null=True, upload_to='author/%Y/%m/%d', verbose_name='Avtor rasmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Kitobning avtor(avtorlar)ini tanlang', to='catalog.author', verbose_name='Kitobning Avtor (Avtorlari)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Janrini tanlang', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Kitobning janri'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text="Uzunligi 13 ta belgidan iborat bo'lishi shart", max_length=13, verbose_name='Kitobning ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Kitobning tilini tanglang!', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Kitobning tili'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(help_text='Kitobning rasmini kiriting!', upload_to='Books', verbose_name='Kitobning rasmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Kitobning narxini kiriting!', max_digits=7, verbose_name='Narxi (sum)!'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(help_text='Nashriyotni tanlang', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.publisher', verbose_name='Kitobning nashriyoti'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='description books', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Kitobning nomini kiriting!', max_length=200, verbose_name='Kitobning nomi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(help_text='Kitobning chiqarilgan yilini kiriting', max_length=4, verbose_name='Kitobning yili'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Kitobning status tugash vaqtini kiriting!', null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='inv_nom',
            field=models.CharField(help_text='Kitobning inventar nomerini kiriting!', max_length=20, null=True, verbose_name='Inventar nomeri'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Kitobning janrini kiriting', max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Kitobning tilini kiriting', max_length=20, verbose_name='Kitobning tili'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='Nashriyotning nomini kiriting!', max_length=20, verbose_name='Nashriyot'),
        ),
    ]
