# Generated by Django 4.2.7 on 2023-11-14 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_alter_author_about_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Kitobning mijozini tanlang', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mijoz'),
        ),
    ]
